sudo: required
sevices:
 - docker

before_install:
 - docker build -t xelooo/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true xelooo/react-test npm test

after_succes:
 - docker build -t xelooo/multi-client ./client
 - docker build -t xelooo/multi-nginx ./nginx
 - docker build -t xelooo/multi-server ./server
 - docker build -t xelooo/multi-worker ./worker
#pushing into docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push xelooo/multi-client
 - docker push xelooo/multi-nginx
 - docker push xelooo/multi-server
 - docker push xelooo/multi-worker
